server.port=9292
spring.datasource.url=jdbc:postgresql://localhost:5432/webshop3d
spring.datasource.username=postgres
spring.datasource.password=docker3d
spring.datasource.driver-class-name=org.postgresql.Driver
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.databaseplatform=org.hibernate.dialect.PostgreSQLDialect
# Show or not log for each sql query
spring.jpa.show-sql=true
# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto=none
# Hibernate will select the payroll schema
spring.jpa.properties.hibernate.default_schema=threed

# To prevent createClob() is not yet implemented. error
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
